<?php

namespace Cms\Modules\Reward\Tests;

use Cms\Modules\Reward\RewardServiceProvider;
use Cms\Modules\Core\Tests\CoreTestCase;

abstract class RewardTestCase extends CoreTestCase
{

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    protected function getPackageProviders($app): array
    {
        return [
            RewardServiceProvider::class,
        ];
    }

    protected function getEnvironmentSetUp($app)
    {
        // perform environment setup
    }
}

