<?php

namespace Cms\Modules\Home\Tests;

use Cms\Modules\Home\HomeServiceProvider;
use Cms\Modules\Core\Tests\CoreTestCase;

abstract class HomeTestCase extends CoreTestCase
{

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    protected function getPackageProviders($app): array
    {
        return [
            HomeServiceProvider::class,
        ];
    }

    protected function getEnvironmentSetUp($app)
    {
        // perform environment setup
    }
}

